"""
Django settings for agrosphere project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
from decouple import config
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Created apps
    'accounts',
    'analytics',
    'blockchain',
    'experts',
    'farming',
    'investments',
    'marketplace',
    'notifications',
    'ussd',

    # Installed libraries
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'storages',
    'drf_spectacular',
    'django_celery_beat'

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'agrosphere.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'agrosphere.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'accounts.User'
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Config
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICAION_CLASSES': [
        'rest_framework_simplejwt.auhentication.JWTAuthentication',
    ],

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',

    'PAGE_SIZE': 20,

    'DEFAULT_FILTER_BACKENDS':[
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],

    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],

    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
        'ai_endpoint': '50/hour',  # Rate limit for AI features
    },

    'EXCEPTION_HANDLER': 'utils.exceptions.custom_exception_handler',
}


# JWT Config
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(
        seconds=config('JWT_ACCESS_TOKEN_LIFETIME', default=3600, cast=int)
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        seconds=config('JWT_REFRESH_TOKEN_LIFETIME', default=604800, cast=int)
    ),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': config('JWT_SECRET_KEY', default=SECRET_KEY),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

# Redis Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.getenv('REDIS_URL'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
            'RETRY_ON_TIMEOUT': True,
            'MAX_CONNECTIONS': 50,
        }
    }
}

# Celery Configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Lagos'
CELERY_BEAT_SCHEDULE = {
    'send-farming-reminders': {
        'task': 'notifications.tasks.send_scheduled_reminders',
        'schedule': timedelta(hours=1),  # Check every hour
    },
    'update-weather-alerts': {
        'task': 'farming.tasks.update_weather_alerts',
        'schedule': timedelta(hours=6),  # Update every 6 hours
    },
    'process-investment-returns': {
        'task': 'investments.tasks.process_matured_investments',
        'schedule': timedelta(days=1),  # Daily processing
    },
}


# AWS S3 Configuration (Optional, for production)
USE_S3 = config('USE_S3', default=False, cast=bool)
if USE_S3:
    AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='us-east-1')
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# CORS Configuration
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS')

CORS_ALLOW_CREDENTIALS = True

# API Documentation (Swagger)
SPECTACULAR_SETTINGS = {
    'TITLE': 'Agrosphere API',
    'DESCRIPTION': 'Comprehensive agricultural ecosystem API with Ethereum blockchain',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

ETHEREUM_CONFIG = {
    'NETWORK': config('ETHEREUM_NETWORK', default='sepolia'),  # mainnet, sepolia, goerli, ganache
    'RPC_URL': config('ETHEREUM_RPC_URL', default='https://sepolia.infura.io/v3/YOUR_PROJECT_ID'),
    'INFURA_PROJECT_ID': config('INFURA_PROJECT_ID', default=''),
    'INFURA_PROJECT_SECRET': config('INFURA_PROJECT_SECRET', default=''),
    'AGROCOIN_CONTRACT_ADDRESS': config('AGROCOIN_CONTRACT_ADDRESS', default=''),
    'TREASURY_WALLET_PRIVATE_KEY': config('TREASURY_WALLET_PRIVATE_KEY', default=''),
    'PLATFORM_FEE_WALLET': config('PLATFORM_FEE_WALLET', default=''),
    'AGROCOIN_TO_NAIRA_RATE': config('AGROCOIN_TO_NAIRA_RATE', default=100, cast=float),
    'GAS_PRICE_GWEI': config('GAS_PRICE_GWEI', default=20, cast=int),
    'GAS_LIMIT': config('GAS_LIMIT', default=100000, cast=int),
    'TRANSACTION_TIMEOUT': 120,  # seconds
    'CHAIN_ID': {
        'mainnet': 1,
        'sepolia': 11155111,
        'goerli': 5,
        'ganache': 1337,
    },
}

# AI Integrations
GEMINI_CONFIG = {
    'API_KEY': os.getenv('GEMINI_API_KEY'),
    'MODEL': config('GEMINI_MODEL', default='gemini-1.5-flash'),
    'TEMPERATURE': 0.7,
    'MAX_OUTPUT_TOKENS': 2048,
}

# Africa's Talking (USSD) Configuration
AFRICAS_TALKING_CONFIG = {
    'USERNAME': os.getenv('AFRICAS_TALKING_USERNAME'),
    'API_KEY': config('AFRICAS_TALKING_API_KEY'),
    'USSD_SHORT_CODE': config('USSD_SHORT_CODE', default='*384*1234#'),
}

# Weather API Configuration
WEATHER_API_KEY = config('OPENWEATHER_API_KEY', default='')


# Email Configuration (SendGrid)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
SENDGRID_API_KEY = config('SENDGRID_API_KEY', default='')
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'apikey'
EMAIL_HOST_PASSWORD = SENDGRID_API_KEY
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')

# SMS Configuration
TWILIO_CONFIG = {
    'ACCOUNT_SID': config('TWILIO_ACCOUNT_SID', default=''),
    'AUTH_TOKEN': config('TWILIO_AUTH_TOKEN', default=''),
    'PHONE_NUMBER': config('TWILIO_PHONE_NUMBER', default=''),
}

# Feature Flags
ENABLE_WEB3 = config('ENABLE_WEB3', default=True, cast=bool)
ENABLE_USSD = config('ENABLE_USSD', default=True, cast=bool)
ENABLE_AI_FEATURES = config('ENABLE_AI_FEATURES', default=True, cast=bool)
ENABLE_NOTIFICATIONS = config('ENABLE_NOTIFICATIONS', default=True, cast=bool)
DEMO_MODE = config('DEMO_MODE', default=True, cast=bool)

# Platform Settings
PLATFORM_COMMISSION_RATE = 0.05  # 5% commission on transactions
MIN_INVESTMENT_AMOUNT = 5000  # NGN 5,000 minimum investment
MAX_FILE_UPLOAD_SIZE = 5 * 1024 * 1024  # 5MB

# Nigerian Cities (for location-based features)
NIGERIAN_CITIES = [
    'Lagos', 'Abuja', 'Kano', 'Ibadan', 'Port Harcourt',
    'Benin City', 'Jos', 'Kaduna', 'Enugu', 'Aba',
    'Onitsha', 'Warri', 'Ilorin', 'Calabar', 'Akure'
]

# Crop Categories
CROP_CATEGORIES = [
    'Vegetables', 'Fruits', 'Grains', 'Legumes',
    'Tubers', 'Herbs', 'Cash Crops'
]

# Expert Specializations
EXPERT_SPECIALIZATIONS = [
    'Soil Science', 'Veterinary Medicine', 'Agronomy',
    'Crop Science', 'Farm Management', 'Irrigation',
    'Pest Control', 'Organic Farming'
]

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'agromentor360.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}

# Sentry Configuration (Error Tracking)
SENTRY_DSN = config('SENTRY_DSN', default='', cast=str)
if SENTRY_DSN and not DEBUG:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    
    sentry_sdk.init(
        dsn=SENTRY_DSN, #type:ignore
        integrations=[DjangoIntegration()],
        traces_sample_rate=0.1,
        send_default_pii=True
    )

# Security Settings for Production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True